### ISSUE TITLE
Problem with Device Key file for Lunii v3

### ISSUE THREAD

**Issue by stnnnts** [o-daneel/Lunii.PACKS#2]
Hello,

I try to use lunii-pm on macOS. When I type "./lunii-pm -f", I have the following error:
Error: Invalid value for '--pack-import' / '-pi': Path '/Users/XXX/.lunii-qt/v3.keys' does not exist.

I don't know where to get this key file. Could you please help me?

Best regards.

**Comment by o-daneel** [comment]
Oh I think i did a mistake when porting back some changes from Lunii.QT to Lunii.PACKS 😅
Should I suggest to get a previous tag, that should help while I try to fix. Otherwise I recommend to try the GUI version
https://github.com/o-daneel/Lunii.QT

**Comment by o-daneel** [comment]
stupid update on my side... pushing a fix. Default valut for key set on wrong parameter.
Thanks for the feedback

**Comment by o-daneel** [comment]
@stnnnts please validate that fix on main branch is ok for you.

**Comment by stnnnts** [comment]
Thank you. The problem is that I do not know where I can get the required device key file

Best regards.






Le mardi 16 janvier 2024 à 21:01:42 UTC+1, o.Daneel ***@***.***> a écrit : 







Oh I think i did a mistake when porting back some changes from Lunii.QT to Lunii.PACKS 😅
Should I suggest to get a previous tag, that should help while I try to fix. Otherwise I recommend to try the GUI version
https://github.com/o-daneel/Lunii.QT

**Comment by stnnnts** [comment]
Sorry but I only use the binary on macOS. Could you please update the binary as well.

Best regards.






Le mardi 16 janvier 2024 à 21:10:25 UTC+1, o.Daneel ***@***.***> a écrit : 







@stnnnts please validate that fix on main branch is ok for you.

**Comment by o-daneel** [comment]
Pushing a new tag for binary generation. Coming in few minutes.

**Comment by o-daneel** [comment]
New release here :
https://github.com/o-daneel/Lunii.PACKS/releases/tag/v2.0.3

May I get your feedback on the GUI version ?
https://github.com/o-daneel/Lunii.QT/releases/tag/v2.1.1

**Comment by stnnnts** [comment]
Thank you very much. It works perfectly :-)

Best regards.






Le mardi 16 janvier 2024 à 21:19:35 UTC+1, o.Daneel ***@***.***> a écrit : 







New release here :
https://github.com/o-daneel/Lunii.PACKS/releases/tag/v2.0.3

May I get your feedback on the GUI version ?
https://github.com/o-daneel/Lunii.QT/releases/tag/v2.1.1

**Comment by o-daneel** [comment]
v2.0.3 validated
